//! Tailwind v4 theme output generator for collet-tokens.
//!
//! Generates a `tailwind.config.ts` that maps design token CSS custom
//! properties into the Tailwind theme, enabling classes like `bg-primary`,
//! `font-display`, `p-4`, and `rounded-md` to resolve to the token values.

use std::fmt::Write;

use collet_tokens_core::OutputFile;
use collet_tokens_core::types::ResolvedTokens;

/// Generate Tailwind v4 config files from resolved tokens.
///
/// Returns a single [`OutputFile`] containing `tailwind.config.ts`.
#[must_use]
pub fn generate(tokens: &ResolvedTokens) -> Vec<OutputFile> {
    let mut ts = String::with_capacity(2048);

    write_header(&mut ts);
    write_config_open(&mut ts);
    write_colors(tokens, &mut ts);
    write_fonts(tokens, &mut ts);
    write_spacing(tokens, &mut ts);
    write_radius(tokens, &mut ts);
    write_config_close(&mut ts);

    vec![OutputFile {
        path: "tailwind.config.ts".to_owned(),
        content: ts,
    }]
}

/// Write the file header.
fn write_header(ts: &mut String) {
    let _ = writeln!(ts, "// Generated by collet-tokens — do not edit manually");
    let _ = writeln!(ts, "import type {{ Config }} from \"tailwindcss\";");
    let _ = writeln!(ts);
}

/// Write the config export opening.
fn write_config_open(ts: &mut String) {
    let _ = writeln!(ts, "export default {{");
    let _ = writeln!(ts, "  theme: {{");
    let _ = writeln!(ts, "    extend: {{");
}

/// Write color theme entries.
fn write_colors(tokens: &ResolvedTokens, ts: &mut String) {
    if tokens.colors.is_empty() {
        return;
    }
    let _ = writeln!(ts, "      colors: {{");
    for color in &tokens.colors {
        let _ = writeln!(
            ts,
            "        \"{}\": \"var({})\",",
            color.name, color.css_var
        );
    }
    let _ = writeln!(ts, "      }},");
}

/// Write font family theme entries.
fn write_fonts(_tokens: &ResolvedTokens, ts: &mut String) {
    let _ = writeln!(ts, "      fontFamily: {{");
    let _ = writeln!(ts, "        \"display\": \"var(--font-display)\",");
    let _ = writeln!(ts, "        \"body\": \"var(--font-body)\",");
    let _ = writeln!(ts, "        \"mono\": \"var(--font-mono)\",");
    let _ = writeln!(ts, "      }},");
}

/// Write spacing theme entries.
fn write_spacing(tokens: &ResolvedTokens, ts: &mut String) {
    if tokens.spacing.is_empty() {
        return;
    }
    let _ = writeln!(ts, "      spacing: {{");
    for sp in &tokens.spacing {
        let _ = writeln!(ts, "        \"{}\": \"var(--space-{})\",", sp.name, sp.name);
    }
    let _ = writeln!(ts, "      }},");
}

/// Write border radius theme entries.
fn write_radius(tokens: &ResolvedTokens, ts: &mut String) {
    if tokens.radius.is_empty() {
        return;
    }
    let _ = writeln!(ts, "      borderRadius: {{");
    for r in &tokens.radius {
        let _ = writeln!(ts, "        \"{}\": \"var(--radius-{})\",", r.name, r.name);
    }
    let _ = writeln!(ts, "      }},");
}

/// Write the config export closing.
fn write_config_close(ts: &mut String) {
    let _ = writeln!(ts, "    }},");
    let _ = writeln!(ts, "  }},");
    let _ = writeln!(ts, "}} satisfies Config;");
}

#[cfg(test)]
mod tests {
    use super::*;
    use collet_tokens_core::OklchColor;
    use collet_tokens_core::types::{
        ResolvedColor, ResolvedFonts, ResolvedMotion, ResolvedRadius, ResolvedSpacing,
    };
    use std::collections::BTreeMap;

    fn minimal_tokens() -> ResolvedTokens {
        ResolvedTokens {
            fonts: ResolvedFonts {
                display: "'Inter', sans-serif".to_owned(),
                body: "'Inter', sans-serif".to_owned(),
                mono: "'JetBrains Mono', monospace".to_owned(),
            },
            colors: vec![ResolvedColor {
                name: "primary".to_owned(),
                css_var: "--color-primary".to_owned(),
                light: OklchColor::new(0.55, 0.25, 264.0),
                dark: OklchColor::new(0.65, 0.20, 264.0),
                light_css: "oklch(0.55 0.25 264)".to_owned(),
                dark_css: "oklch(0.65 0.2 264)".to_owned(),
            }],
            typography: vec![],
            spacing: vec![ResolvedSpacing {
                name: "4".to_owned(),
                value_rem: 1.0,
                value_px: 16.0,
            }],
            radius: vec![ResolvedRadius {
                name: "md".to_owned(),
                value: "0.5rem".to_owned(),
            }],
            motion: ResolvedMotion {
                durations: BTreeMap::new(),
                easings: BTreeMap::new(),
            },
        }
    }

    #[test]
    fn generates_single_file() {
        let files = generate(&minimal_tokens());
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].path, "tailwind.config.ts");
    }

    #[test]
    fn contains_color_mapping() {
        let files = generate(&minimal_tokens());
        assert!(
            files[0]
                .content
                .contains("\"primary\": \"var(--color-primary)\"")
        );
    }

    #[test]
    fn contains_font_mapping() {
        let files = generate(&minimal_tokens());
        assert!(
            files[0]
                .content
                .contains("\"display\": \"var(--font-display)\"")
        );
        assert!(files[0].content.contains("\"body\": \"var(--font-body)\""));
        assert!(files[0].content.contains("\"mono\": \"var(--font-mono)\""));
    }

    #[test]
    fn contains_spacing_mapping() {
        let files = generate(&minimal_tokens());
        assert!(files[0].content.contains("\"4\": \"var(--space-4)\""));
    }

    #[test]
    fn contains_radius_mapping() {
        let files = generate(&minimal_tokens());
        assert!(files[0].content.contains("\"md\": \"var(--radius-md)\""));
    }

    #[test]
    fn is_valid_typescript_structure() {
        let files = generate(&minimal_tokens());
        let content = &files[0].content;
        assert!(content.contains("import type { Config }"));
        assert!(content.contains("export default {"));
        assert!(content.contains("} satisfies Config;"));
    }
}
