//! CSS custom property output generator for collet-tokens.
//!
//! Generates a single `tokens.css` file from [`ResolvedTokens`] containing:
//! - `:root {}` block with all light-mode custom properties
//! - `@media (prefers-color-scheme: dark) { :root {} }` with dark-mode color overrides
//! - Typography utility classes (`.t-display`, `.t-h1`, ..., `.t-code`)
//! - Modifier classes (`.t--muted`, `.t--strong`, etc.)

use std::fmt::Write;

use collet_tokens_core::OutputFile;
use collet_tokens_core::types::ResolvedTokens;

/// Format a floating-point value as a rem string with minimal precision.
///
/// Uses up to 4 decimal places, then strips trailing zeros:
/// `0.2500` → `0.25rem`, `1.0000` → `1rem`.
fn fmt_rem(val: f64) -> String {
    let s = format!("{val:.4}");
    let trimmed = s.trim_end_matches('0').trim_end_matches('.');
    format!("{trimmed}rem")
}

/// Generate CSS output files from resolved tokens.
///
/// Returns a single [`OutputFile`] containing the complete `tokens.css`.
#[must_use]
pub fn generate(tokens: &ResolvedTokens) -> Vec<OutputFile> {
    let mut css = String::with_capacity(4096);

    write_header(&mut css);
    write_light_root(tokens, &mut css);
    write_dark_overrides(tokens, &mut css);
    write_typography_classes(tokens, &mut css);
    write_modifier_classes(&mut css);

    vec![OutputFile {
        path: "tokens.css".to_owned(),
        content: css,
    }]
}

/// Write the file header comment.
fn write_header(css: &mut String) {
    let _ = writeln!(
        css,
        "/* Generated by collet-tokens — do not edit manually */"
    );
    let _ = writeln!(css);
}

/// Write the `:root {}` block with all light-mode custom properties.
fn write_light_root(tokens: &ResolvedTokens, css: &mut String) {
    let _ = writeln!(css, ":root {{");

    // Fonts
    let _ = writeln!(css, "  /* Fonts */");
    let _ = writeln!(css, "  --font-display: {};", tokens.fonts.display);
    let _ = writeln!(css, "  --font-body: {};", tokens.fonts.body);
    let _ = writeln!(css, "  --font-mono: {};", tokens.fonts.mono);
    let _ = writeln!(css);

    // Colors (light mode)
    if !tokens.colors.is_empty() {
        let _ = writeln!(css, "  /* Colors (light mode) */");
        for color in &tokens.colors {
            let _ = writeln!(css, "  {}: {};", color.css_var, color.light_css);
        }
        let _ = writeln!(css);
    }

    // Spacing
    if !tokens.spacing.is_empty() {
        let _ = writeln!(css, "  /* Spacing */");
        for sp in &tokens.spacing {
            let _ = writeln!(css, "  --space-{}: {};", sp.name, fmt_rem(sp.value_rem));
        }
        let _ = writeln!(css);
    }

    // Radius
    if !tokens.radius.is_empty() {
        let _ = writeln!(css, "  /* Radius */");
        for r in &tokens.radius {
            let _ = writeln!(css, "  --radius-{}: {};", r.name, r.value);
        }
        let _ = writeln!(css);
    }

    // Motion — durations
    if !tokens.motion.durations.is_empty() {
        let _ = writeln!(css, "  /* Motion — durations */");
        for (name, value) in &tokens.motion.durations {
            let _ = writeln!(css, "  --duration-{name}: {value};");
        }
        let _ = writeln!(css);
    }

    // Motion — easings
    if !tokens.motion.easings.is_empty() {
        let _ = writeln!(css, "  /* Motion — easings */");
        for (name, value) in &tokens.motion.easings {
            let _ = writeln!(css, "  --ease-{name}: {value};");
        }
        let _ = writeln!(css);
    }

    let _ = writeln!(css, "}}");
    let _ = writeln!(css);
}

/// Write `@media (prefers-color-scheme: dark)` overrides.
fn write_dark_overrides(tokens: &ResolvedTokens, css: &mut String) {
    if tokens.colors.is_empty() {
        return;
    }

    let _ = writeln!(css, "@media (prefers-color-scheme: dark) {{");
    let _ = writeln!(css, "  :root {{");
    for color in &tokens.colors {
        let _ = writeln!(css, "    {}: {};", color.css_var, color.dark_css);
    }
    let _ = writeln!(css, "  }}");
    let _ = writeln!(css, "}}");
    let _ = writeln!(css);
}

/// Write typography utility classes (`.t-display`, `.t-h1`, etc.).
fn write_typography_classes(tokens: &ResolvedTokens, css: &mut String) {
    if tokens.typography.is_empty() {
        return;
    }

    let _ = writeln!(css, "/* Typography utility classes */");
    let _ = writeln!(css);

    for role in &tokens.typography {
        let _ = writeln!(css, ".t-{} {{", role.name);
        for (prop, value) in &role.css_properties {
            let _ = writeln!(css, "  {prop}: {value};");
        }
        let _ = writeln!(css, "}}");
        let _ = writeln!(css);
    }
}

/// Write typography modifier classes.
fn write_modifier_classes(css: &mut String) {
    let _ = writeln!(css, "/* Typography modifiers */");
    let _ = writeln!(css);

    let _ = writeln!(css, ".t--muted {{");
    let _ = writeln!(css, "  opacity: 0.6;");
    let _ = writeln!(css, "}}");
    let _ = writeln!(css);

    let _ = writeln!(css, ".t--strong {{");
    let _ = writeln!(css, "  font-weight: 700;");
    let _ = writeln!(css, "}}");
    let _ = writeln!(css);

    let _ = writeln!(css, ".t--italic {{");
    let _ = writeln!(css, "  font-style: italic;");
    let _ = writeln!(css, "}}");
    let _ = writeln!(css);

    let _ = writeln!(css, ".t--underline {{");
    let _ = writeln!(css, "  text-decoration: underline;");
    let _ = writeln!(css, "  text-underline-offset: 0.15em;");
    let _ = writeln!(css, "}}");
    let _ = writeln!(css);

    let _ = writeln!(css, ".t--underline-strong {{");
    let _ = writeln!(css, "  text-decoration: underline;");
    let _ = writeln!(css, "  text-decoration-thickness: 2px;");
    let _ = writeln!(css, "  text-underline-offset: 0.15em;");
    let _ = writeln!(css, "}}");
    let _ = writeln!(css);

    let _ = writeln!(css, ".t--truncate {{");
    let _ = writeln!(css, "  overflow: hidden;");
    let _ = writeln!(css, "  text-overflow: ellipsis;");
    let _ = writeln!(css, "  white-space: nowrap;");
    let _ = writeln!(css, "}}");
    let _ = writeln!(css);
}

#[cfg(test)]
mod tests {
    use super::*;
    use collet_tokens_core::OklchColor;
    use collet_tokens_core::types::{
        ResolvedColor, ResolvedFonts, ResolvedMotion, ResolvedRadius, ResolvedSpacing,
        ResolvedTypeRole,
    };
    use std::collections::BTreeMap;

    fn minimal_tokens() -> ResolvedTokens {
        ResolvedTokens {
            fonts: ResolvedFonts {
                display: "'Inter', sans-serif".to_owned(),
                body: "'Inter', sans-serif".to_owned(),
                mono: "'JetBrains Mono', monospace".to_owned(),
            },
            colors: vec![ResolvedColor {
                name: "surface".to_owned(),
                css_var: "--color-surface".to_owned(),
                light: OklchColor::new(1.0, 0.0, 0.0),
                dark: OklchColor::new(0.13, 0.0, 0.0),
                light_css: "oklch(1 0 0)".to_owned(),
                dark_css: "oklch(0.13 0 0)".to_owned(),
            }],
            typography: vec![{
                let mut props = BTreeMap::new();
                props.insert("font-size".to_owned(), "1.0000rem".to_owned());
                props.insert("font-weight".to_owned(), "400".to_owned());
                props.insert("line-height".to_owned(), "1.6".to_owned());
                props.insert("letter-spacing".to_owned(), "0em".to_owned());
                props.insert("font-family".to_owned(), "var(--font-body)".to_owned());
                ResolvedTypeRole {
                    name: "body-md".to_owned(),
                    css_properties: props,
                    fluid_size: None,
                }
            }],
            spacing: vec![ResolvedSpacing {
                name: "1".to_owned(),
                value_rem: 0.25,
                value_px: 4.0,
            }],
            radius: vec![ResolvedRadius {
                name: "md".to_owned(),
                value: "0.5rem".to_owned(),
            }],
            motion: ResolvedMotion {
                durations: {
                    let mut m = BTreeMap::new();
                    m.insert("fast".to_owned(), "100ms".to_owned());
                    m
                },
                easings: {
                    let mut m = BTreeMap::new();
                    m.insert("linear".to_owned(), "linear".to_owned());
                    m
                },
            },
        }
    }

    #[test]
    fn generates_single_file() {
        let files = generate(&minimal_tokens());
        assert_eq!(files.len(), 1);
        assert_eq!(files[0].path, "tokens.css");
    }

    #[test]
    fn contains_root_block() {
        let files = generate(&minimal_tokens());
        assert!(files[0].content.contains(":root {"));
    }

    #[test]
    fn contains_font_vars() {
        let files = generate(&minimal_tokens());
        assert!(files[0].content.contains("--font-display:"));
        assert!(files[0].content.contains("--font-body:"));
        assert!(files[0].content.contains("--font-mono:"));
    }

    #[test]
    fn contains_color_vars_light() {
        let files = generate(&minimal_tokens());
        assert!(files[0].content.contains("--color-surface: oklch(1 0 0)"));
    }

    #[test]
    fn contains_dark_mode_override() {
        let files = generate(&minimal_tokens());
        assert!(files[0].content.contains("prefers-color-scheme: dark"));
        assert!(
            files[0]
                .content
                .contains("--color-surface: oklch(0.13 0 0)")
        );
    }

    #[test]
    fn contains_typography_class() {
        let files = generate(&minimal_tokens());
        assert!(files[0].content.contains(".t-body-md {"));
    }

    #[test]
    fn contains_modifier_classes() {
        let files = generate(&minimal_tokens());
        let css = &files[0].content;
        assert!(css.contains(".t--muted {"));
        assert!(css.contains(".t--strong {"));
        assert!(css.contains(".t--italic {"));
        assert!(css.contains(".t--underline {"));
        assert!(css.contains(".t--underline-strong {"));
        assert!(css.contains(".t--truncate {"));
    }

    #[test]
    fn contains_spacing_vars() {
        let files = generate(&minimal_tokens());
        assert!(files[0].content.contains("--space-1: 0.25rem"));
    }

    #[test]
    fn contains_radius_vars() {
        let files = generate(&minimal_tokens());
        assert!(files[0].content.contains("--radius-md: 0.5rem"));
    }

    #[test]
    fn contains_motion_vars() {
        let files = generate(&minimal_tokens());
        assert!(files[0].content.contains("--duration-fast: 100ms"));
        assert!(files[0].content.contains("--ease-linear: linear"));
    }
}
